language: go
go:
  - tip
script:
  - go build
  - go get golang.org/x/tools/cmd/cover
  - go test -v -covermode=count -coverprofile=coverage.out $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN